
option('qemu_suffix', type : 'string', value: 'qemu')
option('docdir', type : 'string', value : 'share/doc')
option('qemu_firmwarepath', type : 'array', value : ['share/qemu-firmware'])
option('pkgversion', type : 'string', value : '')
option('iasl', type : 'string', value : '')
option('tls_priority', type : 'string', value : 'NORMAL')
option('default_devices', type : 'boolean', value : true)
option('audio_drv_list', type: 'array', value: ['aaudio'],
       choices: ['aaudio', 'alsa', 'coreaudio', 'default', 'dsound', 'jack', 'oss', 'pa', 'pipewire', 'sdl', 'sndio'])
option('block_drv_rw_whitelist', type : 'string', value : '')
option('block_drv_ro_whitelist', type : 'string', value : '')
option('interp_prefix', type : 'string', value : '/usr/gnemul/qemu-%M')
option('rtsig_map', type : 'string', value : 'NULL')
option('fuzzing_engine', type : 'string', value : '')
option('trace_file', type: 'string', value: 'trace')
option('coroutine_backend', type: 'combo',
       choices: ['ucontext', 'sigaltstack', 'windows', 'auto'],
       value: 'sigaltstack')

# Everything else can be set via --enable/--disable-* option
# on the configure script command line.  After adding an option
# here make sure to run "make update-buildoptions".

option('docs', type : 'feature', value : 'disabled')
option('fuzzing', type : 'boolean', value: false)
option('modules', type : 'feature', value : 'disabled')
option('module_upgrades', type : 'boolean', value : false)
option('install_blobs', type : 'boolean', value : true)
option('sparse', type : 'feature', value : 'auto')
option('guest_agent', type : 'feature', value : 'disabled')
option('guest_agent_msi', type : 'feature', value : 'disabled')
option('tools', type : 'feature', value : 'disabled')
option('qga_vss', type : 'feature', value: 'auto')

option('malloc_trim', type : 'feature', value : 'auto')
option('malloc', type : 'combo', choices : ['system', 'tcmalloc', 'jemalloc'],
       value: 'system')

option('gunyah', type: 'feature', value: 'auto')
option('xen', type: 'feature', value: 'disabled')
option('xen_pci_passthrough', type: 'feature', value: 'disabled')
option('plugins', type: 'boolean', value: false)
option('debug_remap', type: 'boolean', value: false)
option('safe_stack', type: 'boolean', value: false)
option('asan', type: 'boolean', value: false)
option('ubsan', type: 'boolean', value: false)
option('tsan', type: 'boolean', value: false)
option('stack_protector', type: 'feature', value: 'auto')
option('cfi', type: 'boolean', value: false)
option('cfi_debug', type: 'boolean', value: false)
option('multiprocess', type: 'feature', value: 'disabled')
option('relocatable', type : 'boolean', value : true)
option('dbus_display', type: 'feature', value: 'disabled')

# Do not enable it by default even for Mingw32, because it doesn't
option('membarrier', type: 'feature', value: 'disabled')

option('avx2', type: 'feature', value: 'auto')
option('avx512bw', type: 'feature', value: 'auto')
option('attr', type : 'feature', value : 'disabled')
option('brlapi', type : 'feature', value : 'auto')
option('bzip2', type : 'feature', value : 'auto')
option('cap_ng', type : 'feature', value : 'auto')
option('blkio', type : 'feature', value : 'auto')
option('cocoa', type : 'feature', value : 'disabled')
option('curl', type : 'feature', value : 'auto')
option('gio', type : 'feature', value : 'auto')
option('libdw', type : 'feature', value : 'auto')
option('iconv', type : 'feature', value : 'auto')
option('curses', type : 'feature', value : 'disabled')
option('libcbor', type : 'feature', value : 'auto')
option('gnutls', type : 'feature', value : 'disabled')
option('nettle', type : 'feature', value : 'auto')
option('gcrypt', type : 'feature', value : 'disabled')
option('crypto_afalg', type : 'feature', value : 'disabled')
option('libdaxctl', type : 'feature', value : 'auto')
option('libpmem', type : 'feature', value : 'auto')
option('libudev', type : 'feature', value : 'auto')
option('libusb', type : 'feature', value : 'disabled')
option('linux_io_uring', type : 'feature', value : 'auto')
option('lzfse', type : 'feature', value : 'auto')
option('lzo', type : 'feature', value : 'auto')
option('pvg', type: 'feature', value: 'auto')
option('opengl', type : 'feature', value : 'auto')
option('sdl', type : 'feature', value : 'auto')
option('seccomp', type : 'feature', value : 'auto')
option('smartcard', type : 'feature', value : 'auto')
option('snappy', type : 'feature', value : 'auto')
option('spice', type : 'feature', value : 'auto')
option('spice_protocol', type : 'feature', value : 'auto')
option('u2f', type : 'feature', value : 'auto')
option('l2tpv3', type : 'feature', value : 'disabled')
option('pixman', type : 'feature', value : 'auto')
option('vde', type : 'feature', value : 'auto')
option('virglrenderer', type : 'feature', value : 'auto')
option('png', type : 'feature', value : 'auto')
option('xkbcommon', type : 'feature', value : 'auto')
option('zstd', type : 'feature', value : 'disabled')
option('qpl', type : 'feature', value : 'auto')
option('uadk', type : 'feature', value : 'auto')
option('qatzip', type: 'feature', value: 'auto')
option('trace_backends', type: 'array', value: ['nop'],
       choices: ['dtrace', 'ftrace', 'log', 'nop', 'simple', 'syslog', 'ust'])

option('alsa', type: 'feature', value: 'auto')
option('coreaudio', type: 'feature', value: 'auto')
option('dsound', type: 'feature', value: 'auto')
option('jack', type: 'feature', value: 'auto')
option('oss', type: 'feature', value: 'auto')
option('pa', type: 'feature', value: 'auto')
option('pipewire', type: 'feature', value: 'auto')
option('sndio', type: 'feature', value: 'auto')

option('virtfs', type: 'feature', value: 'disabled')

option('capstone', type: 'feature', value: 'disabled')
option('fdt', type: 'combo', value: 'auto',
       choices: ['disabled', 'enabled', 'auto', 'system', 'internal'])

option('replication', type: 'feature', value: 'disabled')
option('block_drv_whitelist_in_tools', type: 'boolean', value: false)
option('rng_none', type: 'boolean', value: false)
option('coroutine_pool', type: 'boolean', value: false)
option('debug_graph_lock', type: 'boolean', value: false)
option('debug_mutex', type: 'boolean', value: false)
option('debug_stack_usage', type: 'boolean', value: false)
option('qom_cast_debug', type: 'boolean', value: true)
option('qemu_ga_manufacturer', type: 'string', value: 'QEMU')
option('qemu_ga_distro', type: 'string', value: 'Linux')
option('qemu_ga_version', type: 'string', value: '')

option('hexagon_idef_parser', type : 'boolean', value : true)

option('x86_version', type : 'combo', choices : ['0', '1', '2', '3', '4'], value: '1')

option('rust', type: 'feature', value: 'disabled')
option('strict_rust_lints', type: 'boolean', value: false)
