#ifndef PC_HOTPLUG_H
#define PC_HOTPLUG_H


#define ACPI_CPU_HOTPLUG_ID_LIMIT 256

#define ACPI_GPE_PROC_LEN 32

#define ICH9_CPU_HOTPLUG_IO_BASE 0x0CD8
#define PIIX4_CPU_HOTPLUG_IO_BASE 0xaf00
#define CPU_HOTPLUG_RESOURCE_DEVICE PRES

#define ACPI_MEMORY_HOTPLUG_BASE 0x0a00

#endif
