
#ifndef CPU_INTERRUPT_H
#define CPU_INTERRUPT_H


#define CPU_INTERRUPT_HARD        0x0002

#define CPU_INTERRUPT_EXITTB      0x0004

#define CPU_INTERRUPT_HALT        0x0020

#define CPU_INTERRUPT_DEBUG       0x0080

#define CPU_INTERRUPT_RESET       0x0400

#define CPU_INTERRUPT_TGT_EXT_0   0x0008
#define CPU_INTERRUPT_TGT_EXT_1   0x0010
#define CPU_INTERRUPT_TGT_EXT_2   0x0040
#define CPU_INTERRUPT_TGT_EXT_3   0x0200
#define CPU_INTERRUPT_TGT_EXT_4   0x1000

#define CPU_INTERRUPT_TGT_INT_0   0x0100
#define CPU_INTERRUPT_TGT_INT_1   0x0800
#define CPU_INTERRUPT_TGT_INT_2   0x2000


#define CPU_INTERRUPT_SSTEP_MASK \
    (CPU_INTERRUPT_HARD          \
     | CPU_INTERRUPT_TGT_EXT_0   \
     | CPU_INTERRUPT_TGT_EXT_1   \
     | CPU_INTERRUPT_TGT_EXT_2   \
     | CPU_INTERRUPT_TGT_EXT_3   \
     | CPU_INTERRUPT_TGT_EXT_4)

#endif /* CPU_INTERRUPT_H */
