subdir('acpi')
subdir('audio')
subdir('block')
subdir('char')
subdir('core')
subdir('cpu')
subdir('display')
subdir('gpio')
subdir('hyperv')
subdir('input')
subdir('intc')
subdir('mem')
subdir('misc')
subdir('net')
subdir('nvram')
subdir('pci')
subdir('pci-bridge')
subdir('pci-host')
subdir('rtc')
subdir('smbios')
subdir('uefi')
subdir('usb')
subdir('virtio')
subdir('watchdog')

subdir('arm')
